### ISSUE TITLE
RuntimeError: selected index k out of range

### ISSUE THREAD

**Issue by willer-lu** [XiaoxinHe/G-Retriever#10]
When I do `python -m src.dataset.webqsp`, I encounter the following error:

  0%|          | 0/4700 [00:00<?, ?it/s]
  0%|          | 1/4700 [00:00<56:06,  1.40it/s]
  0%|          | 2/4700 [00:00<32:35,  2.40it/s]
  0%|          | 3/4700 [00:01<21:58,  3.56it/s]
  0%|          | 3/4700 [00:01<28:47,  2.72it/s]
Traceback (most recent call last):
  File "/hpc_stor03/sjtu_home/-/anaconda3/envs/gretriever/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/hpc_stor03/sjtu_home/-/anaconda3/envs/gretriever/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/hpc_stor/hpc_stor03/sjtu_home/-/remote/G-Retriever/src/dataset/webqsp.py", line 82, in <module>
    preprocess()
  File "/hpc_stor/hpc_stor03/sjtu_home/-/remote/G-Retriever/src/dataset/webqsp.py", line 75, in preprocess
    subg, desc = retrieval_via_pcst(graph, q_emb, nodes, edges, topk=3, topk_e=5, cost_e=0.5)
  File "/hpc_stor/hpc_stor03/sjtu_home/-/remote/G-Retriever/src/dataset/utils/retrieval.py", line 21, in retrieval_via_pcst
    _, topk_n_indices = torch.topk(n_prizes, topk, largest=True)
RuntimeError: selected index k out of range

**Comment by XiaoxinHe** [comment]
Could you please pull the latest repo and run the command again to check if the error has been fixed? Thank you!

**Comment by XiaoxinHe** [comment]
Please feel free to reopen it if you have any further questions. Thank you

**Comment by willer-lu** [comment]
> Could you please pull the latest repo and run the command again to check if the error has been fixed? Thank you!

A totally identical error.

**Comment by XiaoxinHe** [comment]
Hi,

The codes seem to work well from my side.

`python -m src.dataset.preprocess.webqsp`
<img width="1073" alt="Screenshot 2024-06-02 at 17 51 07" src="https://github.com/XiaoxinHe/G-Retriever/assets/48676630/46dada04-fbe6-4e3e-a77e-22e5c531309b">

`python -m src.dataset.webqsp`
<img width="1071" alt="Screenshot 2024-06-02 at 18 18 15" src="https://github.com/XiaoxinHe/G-Retriever/assets/48676630/253f7b87-5b5d-4cac-a8f4-36aa89d3cb73">


Therefore, I suggest printing the index of the data where the program gives an error to locate the problem more precisely. Thank you!

**Comment by willer-lu** [comment]
> Hi,
> 
> The codes seem to work well from my side.
> 
> `python -m src.dataset.preprocess.webqsp` <img alt="Screenshot 2024-06-02 at 17 51 07" width="1073" src="https://private-user-images.githubusercontent.com/48676630/335854973-46dada04-fbe6-4e3e-a77e-22e5c531309b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzMzMDEsIm5iZiI6MTcxNzMzMzAwMSwicGF0aCI6Ii80ODY3NjYzMC8zMzU4NTQ5NzMtNDZkYWRhMDQtZmJlNi00ZTNlLWE3N2UtMjJlNWM1MzEzMDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDEyNTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1YjM3MGE2MDgwZTgyZmIxZWU1YTM2MjA4NTlhZjJiZjkyODMxNTNjNDM5MTdlOTE4NmM1OTQ5YWViOTJmMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P-Flc0x3G8tKCz2993YVi0CYZu7ijoMZ3dnwIT3ELuI">
> 
> `python -m src.dataset.webqsp` <img alt="Screenshot 2024-06-02 at 18 18 15" width="1071" src="https://private-user-images.githubusercontent.com/48676630/335856479-253f7b87-5b5d-4cac-a8f4-36aa89d3cb73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzMzMDEsIm5iZiI6MTcxNzMzMzAwMSwicGF0aCI6Ii80ODY3NjYzMC8zMzU4NTY0NzktMjUzZjdiODctNWI1ZC00Y2FjLWE4ZjQtMzZhYTg5ZDNjYjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDEyNTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ZmExZTc0ZmVjY2Y4NTVhZmU4M2NjZjc4MGE5ODViYmRjMDU0MmIxMzgwODRhMzdmOTY5MTZmMzkwNTJmOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qv9vb3wgoLVN9v9mR8laB3HSCu54dwGmQqotpsxIqu8">
> 
> Therefore, I suggest printing the index of the data where the program gives an error to locate the problem more precisely. Thank you!

I try to print some info, I don't know if it can help find where the error lies:

> graph: Data(x=[0, 1024], edge_index=[2, 5734], edge_attr=[5734, 1024], num_nodes=1988)
> nodes:       node_id                 node_attr
> 0           0           hurricane betsy
> 1           1          tropical cyclone
> 2           2  united states of america
> 3           3          hurricane isabel
> 4           4                   bahamas
> ...       ...                       ...
> 1983     1983               g.1245znx5s
> 1984     1984               g.1255g2dwb
> 1985     1985               g.1hhc3pyfb
> 1986     1986                 m.06w5n6q
> 1987     1987               g.1hhc3n9ms
> 
> [1988 rows x 2 columns]
> edges:       src                                          edge_attr  dst
> 0       0                         common.topic.notable_types    1
> 1       2         meteorology.cyclone_affected_area.cyclones    3
> 2       4  location.statistical_region.co2_emissions_per_...    5
> 3       6        meteorology.tropical_cyclone.affected_areas    4
> 4       2             location.country.first_level_divisions    7
> ...   ...                                                ...  ...
> 5729  717        measurement_unit.dated_money_value.currency  194
> 5730  283        meteorology.tropical_cyclone.affected_areas  509
> 5731  337                         common.topic.notable_types    1
> 5732  536         meteorology.cyclone_affected_area.cyclones  586
> 5733  120                                   rdf-schema#range  205
> 
> [5734 rows x 3 columns]
> q_emb: tensor([-0.0481, -0.0108,  0.0025,  ..., -0.0158,  0.0186, -0.0183])
> n_prizes: tensor([])
> topk: 3

**Comment by yucheny5** [comment]
I meet the same issue. Could the author rerun the code from scratch instead of the existing processed dataset to check the error?

**Comment by XiaoxinHe** [comment]
Hi,

This issue is trigger by the graph where graph.x.size(0)==0 but graph.num_nodes!=0, and was likely due to a OOM error happened during preprocessing. It was likely caused by an OOM error during preprocessing. Could you please check if your program enters the except branch during preprocessing at [this line](https://github.com/XiaoxinHe/G-Retriever/blob/f6f530755d1aaf84643349fdbd96e26b1c322291/src/utils/lm_modeling.py#L133)? If so, please decrease the batch size until it fits into your memory and rerun the preprocessing. Thank you!

**Comment by lingvisa** [comment]
@XiaoxinHe I reported here:
1) python3 -m src.dataset.preprocess.webqsp
The result looks good since no error is repoted:
....
# train samples:  2826
# val samples:  246
# test samples:  1628

2) python -m src.dataset.webqsp
I got this error message:

(venv) (base) I747411@YP6VW64HVJ G-Retriever % python3 -m src.dataset.webqsp
/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py:127: **RuntimeWarning: 'src.dataset.webqsp' found in sys.modules after import of package 'src.dataset', but prior to execution of 'src.dataset.webqsp'; this may result in unpredictable behaviour**
```
  warn(RuntimeWarning(msg))
  0%|                                                                                                                                                                                                               | 0/4700 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/I747411/ai/g-retrieval/G-Retriever/src/dataset/webqsp.py", line 82, in <module>
    preprocess()
  File "/Users/I747411/ai/g-retrieval/G-Retriever/src/dataset/webqsp.py", line 74, in preprocess
    q_emb = q_embs[index]
IndexError: index 0 is out of bounds for dimension 0 with size 0

```

**Comment by lingvisa** [comment]
It seems the error is different from the first error reported in this issue. Can you please confirm the result from my first step is correct as reported above? @XiaoxinHe
train samples: 2826
val samples: 246
test samples: 1628

**Comment by luyanchang** [comment]
> @XiaoxinHe I reported here:
> 
> 1. python3 -m src.dataset.preprocess.webqsp
>    The result looks good since no error is repoted:
>    ....
> 
> # train samples: 2826
> # val samples: 246
> # test samples: 1628
> 2. python -m src.dataset.webqsp
>    I got this error message:
> 
> (venv) (base) I747411@YP6VW64HVJ G-Retriever % python3 -m src.dataset.webqsp /opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py:127: **RuntimeWarning: 'src.dataset.webqsp' found in sys.modules after import of package 'src.dataset', but prior to execution of 'src.dataset.webqsp'; this may result in unpredictable behaviour**
> 
> ```
>   warn(RuntimeWarning(msg))
>   0%|                                                                                                                                                                                                               | 0/4700 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/Users/I747411/ai/g-retrieval/G-Retriever/src/dataset/webqsp.py", line 82, in <module>
>     preprocess()
>   File "/Users/I747411/ai/g-retrieval/G-Retriever/src/dataset/webqsp.py", line 74, in preprocess
>     q_emb = q_embs[index]
> IndexError: index 0 is out of bounds for dimension 0 with size 0
> ```

Hello, have you solved this problem?
    subg, desc = retrieval_via_pcst(graph, q_embs[index], nodes, edges, topk=3, topk_e=3, cost_e=0.5)
IndexError: index 0 is out of bounds for dimension 0 with size 0

**Comment by XiaoxinHe** [comment]
Hi,

It seems that in your case, the q_embs is empty. Could you please verify it?

If it is indeed an empty tensor, the issue is triggered by the following line:
https://github.com/XiaoxinHe/G-Retriever/blob/565cd9d4114e2d0817906964c15bbefc4b00f700/src/dataset/preprocess/webqsp.py#L80

You will then need to reduce the batch size here:
https://github.com/XiaoxinHe/G-Retriever/blob/565cd9d4114e2d0817906964c15bbefc4b00f700/src/utils/lm_modeling.py#L11
