### ISSUE TITLE
Requirements file that includes the versions of libraries

### ISSUE THREAD

**Issue by BM-K** [XiaoxinHe/G-Retriever#15]
Hi, Thanks for the great research.

Could I get a requirements.txt file that includes the versions of libraries like `accelerate` and `transformers`? 

When using the latest versions of the libraries, there is an issue where the value of `shift_labels` changes to random numbers in the code `shift_labels = shift_labels.to(shift_logits.device)` within the `LlamaForCausalLM` class. 

I think this problem is caused by the `device_map='auto'` part.

**Comment by XiaoxinHe** [comment]
Hi,

Thank you for your interest in our work. Here is the [requirements.txt](https://github.com/user-attachments/files/15983934/requirements.txt). 

I hope this helps.
