### ISSUE TITLE
About batch size

### ISSUE THREAD

**Issue by suhu93** [XiaoxinHe/G-Retriever#16]
Hello, thank you very much for your work. I have some questions that I hope you can answer.
Your paper says that the batch size used in the experiment is 4, but the batch size in the code is 8, and the data I ran with 8 is closer to what is shown in the paper, although there are still some shortcomings on the sence dataset.

**Comment by XiaoxinHe** [comment]
Hi, thank you for bringing this to our attention. The correct batch size for training should indeed be 8, as indicated in the code. We apologize for the discrepancy in the paper and will ensure it is corrected in the next revision. The reproduction should not be significantly influenced by the batch size within a certain small range, such as 4 or 8. Therefore, you can choose the most suitable batch size that fits your GPU memory. Please let us know if you encounter any further issues or have additional questions.
