### ISSUE TITLE
Table 6.2 Baseline Results

### ISSUE THREAD

**Issue by Ryan-M-Engel** [XiaoxinHe/G-Retriever#18]
In the main results table 6.2, there are baseline results from Zero-shot, Zero-CoT, CoT-BAG, KAPING, and GraphToken. It is unclear exactly where these results came from. The numbers in this table are not represented in the respective papers, and it also appears that these strategies were not implemented or used in the run.sh script. Can you explain how these results were obtained?

**Comment by timothy-coshin** [comment]
![image](https://github.com/user-attachments/assets/02b48577-2233-4524-9323-31525c35d7e0)
I'm guessing it's something like this I hope the author's confirm.

**Comment by XiaoxinHe** [comment]
Thank you @coshin-ssl . Your interpretation is correct!

We explained how the baselines were implemented in Appendix B2 of our paper.
![Screenshot 2024-10-04 at 3 02 19 PM](https://github.com/user-attachments/assets/516315ff-70cf-4361-a2ec-17aeb2c92da1)
