### ISSUE TITLE
GPU acceleration on Apple silicon devices

### ISSUE THREAD

**Issue by BeritSinger** [XiaoxinHe/G-Retriever#19]
Thank you for this beautiful work!

Unfortunately, running the code example (especially for the WebQSP dataset) takes extremely long on my device (>1000 hours). My issue is related to https://github.com/XiaoxinHe/G-Retriever/issues/7, because also in my case the GPU is not used at all. I think, my device would need to utilize Apple's Metal Performance Shaders 'torch.backends.mps' for GPU acceleration on Apple silicon devices, similar to CUDA. Or is there another solution that you see?

**Comment by XiaoxinHe** [comment]
I’m sorry, but I haven’t experimented with Apple GPUs, so I can’t provide a direct solution. It does sound like utilizing Metal Performance Shaders with torch.backends.mps could be a possible approach. Maybe you can give it a try first and see if it helps.
