### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by fantastic-413** [XiaoxinHe/G-Retriever#2]
这里的tape_前缀文件夹是写错了吗？或者如何获取它？另外run.sh文件里和readme里的inference_llm都写成了inference_ll。
![image](https://github.com/XiaoxinHe/G-Retriever/assets/57306219/b5b02559-ca98-468f-b89c-7d96d199ff04)

**Comment by fantastic-413** [comment]
当我把tape_前缀去掉并尝试运行时，出现以下报错。请问这是什么问题？
![image](https://github.com/XiaoxinHe/G-Retriever/assets/57306219/1abb8fe5-7ef9-4425-8f61-505e67372197)

**Comment by XiaoxinHe** [comment]
Hi,

To use our dataset `expla_graph`, please refer to the data preprocessing section in the readme file.
```
## Data Preprocessing
python -m src.dataset.preprocess.expla_graphs
```

You can verify if the dataset has been successfully preprocessed by running:
```
python -m src.dataset.expla_graphs
```

For the `scene_graph` dataset, you need to first unzip the *.zip file in the folder `dataset/scene_graph`.

Thank you for pointing out the typo regarding `inference_lm` in the `README.md` and `run.sh` files. I have corrected them accordingly. Please update your code with `git pull`.

Could you please check if the codes run smoothly after the data preprocessing step? Feel free to let me know if you have any further questions. Thanks!

**Comment by fantastic-413** [comment]
谢谢解答，目前又遇到了两个问题：

1. 当我在运行`python -m src.dataset.webqsp`时报错：
![image](https://github.com/XiaoxinHe/G-Retriever/assets/57306219/455301ee-7f37-4bec-acef-b23ac667b76c)
我看了`src/dataset/scene_graphs.py`和`src/dataset/webqsp.py`中`preprocess()`函数的对比，发现了以下不同：
![image](https://github.com/XiaoxinHe/G-Retriever/assets/57306219/dd844580-d21f-45df-88fd-473baeaf9554)
请问是这个原因吗？

2. 在论文中，针对`inference only`的清况分为 `query` 和 `textual graph + query`，但在`run.sh`中，归到了`frozen llm + prompt tuning`一类中，这是为什么？
![image](https://github.com/XiaoxinHe/G-Retriever/assets/57306219/6ebb6f05-37f3-4f9b-ab21-8c48023254b7)

**Comment by fantastic-413** [comment]
谢谢解答，目前又遇到了两个问题：

1. 当我在运行`python -m src.dataset.webqsp`时报错，请问该如何解决：
![image](https://github.com/XiaoxinHe/G-Retriever/assets/57306219/455301ee-7f37-4bec-acef-b23ac667b76c)

2. 在论文中，针对`inference only`的清况分为 `query` 和 `textual graph + query`，但在`run.sh`中，归到了`frozen llm + prompt tuning`一类中，这是为什么？
![image](https://github.com/XiaoxinHe/G-Retriever/assets/57306219/6ebb6f05-37f3-4f9b-ab21-8c48023254b7)

**Comment by XiaoxinHe** [comment]
Hi,

For Q1, I didn't encounter the same issue as you. Could you please check if you have successfully run the preprocessing with the command `python -m src.dataset.preprocess.webqsp` before `python -m src.dataset.webqsp`? It will take hours to finish.

If you have successfully run this command, could you provide more details about the issue? For example, if the program runs smoothly, there should be a progress bar indicating the process. Does the error occur at the very beginning (when dealing with the first data sample), or in the middle (maybe you could provide the concrete data sample ID)?

For Q2, the command in the run.sh file is a bit misleading. The setting a) "query in frozen llm + prompt tuning" is actually a command for an ablation study. Please ignore it and check out our revised run.sh file.

**Comment by fantastic-413** [comment]
我已经运行python -m src.dataset.preprocess.webqsp获得了处理的数据，
![image](https://github.com/XiaoxinHe/G-Retriever/assets/57306219/aaff5883-23e3-4443-abfc-d4764c754e57)

但是在运行python -m src.dataset.webqsp时报错。​​
![image](https://github.com/XiaoxinHe/G-Retriever/assets/57306219/30bab7dc-933b-434e-9fc7-2a0a771fc13a)

另外对于inference only # a) Question-Only，场景推理任务scene_graphs是不考虑这种情况的吧？

**Comment by XiaoxinHe** [comment]
I have tried rerunning the preprocessing and the PCST retrieval, but I still cannot reproduce the same error. It is kind of strange because if you manually check the file`dataset/webqsp/nodes/3.csv`, there should be almost 2k nodes. The number of nodes is greater than the predefined k(which is 3), and it is unlikely to trigger the error 'selected index k out of range'.

<img width="997" alt="Screenshot 2024-03-06 at 12 09 45" src="https://github.com/XiaoxinHe/G-Retriever/assets/48676630/7624da46-8172-4389-8bea-652c958bc553">

I suggest you debug to find the origins of the error since the logic seems correct from my side.

For inference only # a) Question-Only, yes, you are correct. We do not consider 'question only + scene_graphs' since we cannot answer the question without the scene graph.

**Comment by fantastic-413** [comment]
我尝试打印传入`retrieval_via_pcst`里的一些数据：
![image](https://github.com/XiaoxinHe/G-Retriever/assets/57306219/4625b043-b98f-4c99-8903-c96ee3bb7605)
发现这里`graph.x`为[0,1024]，并且最终得到的`n_prizes`是一个空集，无法理解：
![image](https://github.com/XiaoxinHe/G-Retriever/assets/57306219/f8a1dd60-203d-4d9d-a3b7-bbc327f1862c)
而我的`dataset/webqsp/nodes/3.csv`与您的是一样的：
![image](https://github.com/XiaoxinHe/G-Retriever/assets/57306219/6974501d-8a0b-49d8-8896-bc3064991fb3)

**Comment by XiaoxinHe** [comment]
Yes, then I think here is where the problem arises. Because, as shown in the CSV files, graph.x should have a shape of (1988, 1024). There must be something wrong with the construction of the graph data.

<img width="722" alt="Screenshot 2024-03-06 at 14 21 42" src="https://github.com/XiaoxinHe/G-Retriever/assets/48676630/7f117765-388e-4dcb-95a7-569f017ae0d1">

**Comment by fantastic-413** [comment]
无法理解，我甚至重新运行了`python -m src.dataset.preprocess.webqsp`，仍然得到这样的结果，只有`index=3`有这样的情况，你可以把`graph3.pt`传给我试试吗？
![image](https://github.com/XiaoxinHe/G-Retriever/assets/57306219/a710789d-673a-4c6b-8e21-d07015027932)
![image](https://github.com/XiaoxinHe/G-Retriever/assets/57306219/d99e13b2-6118-4f06-9993-6589068bdf77)

**Comment by XiaoxinHe** [comment]
Here is the link for `3.pt`: https://drive.google.com/file/d/1f55foOsAXof2x_6V79B85rD6Yf8TmRmu/view?usp=sharing. 
Can you check if this helps?

**Comment by fantastic-413** [comment]
结果是不会卡在第3个数据了，但是在第218个数据上出现了相同的问题。我是从`huggingface`上下载的`rmanluo/RoG-webqsp`，我正在尝试重新下载这个数据进行预训练，看看是否还是相同的问题。

**Comment by fantastic-413** [comment]
结果还是一样卡在第3个数据。您的`rmanluo/RoG-webqsp`来自哪里？能否给我试试？事实上，3，218，233，301，335，366，387，398，432，445，473，475，480，598，657，671，856，863，915，919，976，1027，1083，1270，1282，1285，1307，1373，1456，1526，1713，1767，1979，2057，2094，...等等这么多的数据都存在`graph.x.shape[0] == 0`的情况
