### ISSUE TITLE
WebQSP Graph With Zero Node

### ISSUE THREAD

**Issue by timothy-coshin** [XiaoxinHe/G-Retriever#20]
While checking the webqsp data, it is found that there is a graph in the validation data with zero nodes comprising the graph.
This is the reason why your code experiment is not reproducible and gives an error. Please check this part. Thank you.

**Comment by XiaoxinHe** [comment]
Yes, you are right!

As discussed in #13, we need to removed dataset[2937] from the WebQSP data becuase it is an empty graph.

I will try to fix it as soon as possible.

**Comment by timothy-coshin** [comment]
Thank you!
