### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by suhu93** [XiaoxinHe/G-Retriever#21]
![image](https://github.com/user-attachments/assets/ab55cead-5bc9-4e96-bdb5-f58514cf48d4)
Why is it converted to lowercase here? Can it be ignored?

**Comment by XiaoxinHe** [comment]
For the original dataset 'rmanluo/RoG-webqsp', there are instances where the same concept appears in different formats, such as 'gender' and 'Gender'. Converting all instances to lowercase can prevent representing the same concept with two different nodes when constructing a knowledge graph.
