### ISSUE TITLE
关于pcst_fast的一个问题

### ISSUE THREAD

**Issue by 247285** [XiaoxinHe/G-Retriever#24]
在retrieval.py文件中 from pcst_fast import pcst_fast 出现标红，但运行过程中无错误，请问具体原因和解决标红的方法，或者作者可以提供pcst_fast是什么版本吗
![Snipaste_2024-10-03_14-38-20](https://github.com/user-attachments/assets/75a9ff15-183a-42be-a725-6facdfd959bf)

**Comment by XiaoxinHe** [comment]
运行无错误即可？
```
pip install pcst-fast==1.0.10
```

**Comment by 247285** [comment]
十分感谢作者的回复！！！但是无法看到具体是怎么进行检索的吗，pcst_fast的方法进不去
![Snipaste_2024-10-05_12-33-13](https://github.com/user-attachments/assets/c9947dd4-4476-40ab-b80c-6db5338d32e2)

**Comment by 247285** [comment]
> 运行无错误即可？
> 
> ```
> pip install pcst-fast==1.0.10
> ```

十分感谢作者的回复！！！但是无法看到具体是怎么进行检索的吗，pcst_fast的方法进不去
![Snipaste_2024-10-05_12-33-13](https://github.com/user-attachments/assets/35702ef1-0bbc-43bd-9408-4df2453b5888)

**Comment by 247285** [comment]
其实我还有一个疑问关于pcst的，为什么成本大于奖励的时候是实际边，相反要替换成虚拟边，不应该是奖励值越大，成本越低越好吗，十分期待作者的回复

**Comment by XiaoxinHe** [comment]
关于pcst的实现，可参考 https://github.com/fraenkel-lab/pcst_fast

在pcst算法里，对于节点会分配奖励，对边会分配成本。我们希望对边根据语义的相关性，也分配奖励。当奖励<成本时，相当于新成本=成本-奖励；奖励>成本, 因为原算法不支持边上的成本为负，就加入了虚拟节点和虚拟边。把边上的新奖励=奖励-成本，转化为虚拟节点的奖励。
