### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by en1204** [XiaoxinHe/G-Retriever#26]
Hi
How to solve this？
<img width="719" alt="3607cd281ed83cc1a318c6a77db6e4c" src="https://github.com/user-attachments/assets/d7c2e22a-30b6-41ce-9270-a501686197ba">

**Comment by XiaoxinHe** [comment]
Which command did you execute?

**Comment by XiaoxinHe** [comment]
Feel free to reopen the issue if you have any further questions. Thank you!
