### ISSUE TITLE
How did you get the subgraph before getting the top-k relations and nodes?

### ISSUE THREAD

**Issue by ToneLi** [XiaoxinHe/G-Retriever#28]
Hi ,
How did you get the subgraph before getting the top-k relations and nodes?
Best

**Comment by XiaoxinHe** [comment]
It is a user-input graph, which can be a scene graph, knowledge graph, or another type of graph

**Comment by ToneLi** [comment]
how did you get that? its the subgraph within 2-hop?

**Comment by XiaoxinHe** [comment]
For the scene graph, it is not a subgraph but a complete graph constructed from a real image. Details can be found here: https://cs.stanford.edu/people/dorarad/gqa/about.html.

For WebQSP, it is a 2-hop subgraph of a large knowledge graph (KG).

For ExplaGraph, it is not a subgraph but a complete commonsense reasoning graph. Details are available here: https://explagraphs.github.io/.

**Comment by XiaoxinHe** [comment]
Feel free to reopen the issue if you have further questions. Thank you!
