### ISSUE TITLE
I want to apply it to the new dataset

### ISSUE THREAD

**Issue by liqinga** [XiaoxinHe/G-Retriever#4]
Hello, I am very interested in your work and I am using other knowledge graph datasets to run your project. May I ask what is the difference between the ExplaGraphs, SceneGraphs, WebQSP, and regular knowledge graphs you provide? Is my idea feasible? Looking forward to your reply

**Comment by XiaoxinHe** [comment]
Hi,

Thanks for your interest in our work! 

The main difference between the datasets lies in the tasks they are designed for. `ExplaGraphs` focuses on commonsense reasoning, specifically determining whether two arguments support or counter each other. `SceneGraphs` is aimed at scene graph question answering, where the questions primarily concern the relations between objects. `WebQSP` specializes in knowledge-based question answering, which seems to be most relevant to your interests.

If you are considering applying our framework to a new dataset, especially regular knowledge graphs, it is absolutely feasible. Some preprocessing steps you might need include: for a given query, first performing entity linking; then extracting a k-hop subgraph that contains these entities from a large knowledge graph (such as Freebase or Wikipedia), depending on your application. This k-hop subgraph will then serve as the input to our framework. Alternatively, if your knowledge graph is not on a very large scale, you can directly apply our method to your datasets.

Please feel free to let me know if you have further questions.

**Comment by lingvisa** [comment]
"for a given query, first performing entity linking; then extracting a k-hop subgraph that contains these entities from a large knowledge graph (such as Freebase or Wikipedia)":

1) If the query is "Is Obama the president of U.S.? ", what do you by performing entity linking? 
2) "then extracting a k-hop subgraph": Is it one subgraph or multiple subgraph? 

Thank you for explanation!

**Comment by XiaoxinHe** [comment]
You can follow the preprocessing steps here: https://github.com/RichardHGL/WSDM2021_NSM/blob/main/preprocessing/Freebase/README.md

Thanks!
