### ISSUE TITLE
不同Embedding

### ISSUE THREAD

**Issue by gaotongxue12138** [XiaoxinHe/G-Retriever#6]
您好，我在做比较类似的工作，我比较困惑的地方在与构建文本属性Graph时，使用的Embedding模型不同是否会造成不同的影响。我看到 对齐GNN 的输出和基本模型（llama-7B）的语义空间是使用了一个projection。我想问 如果当时对Graph 中的node 进行Embedding的时候，Embedding模型和之后的Base model 的语义空间，差的很大的话，会不会造成效果很差呢

**Comment by gaotongxue12138** [comment]
您好，我在做比较类似的工作，我比较困惑的地方在与构建文本属性Graph时，使用的Embedding模型不同是否会造成不同的影响。我看到 对齐GNN 的输出和基本模型（llama-7B）的语义空间是使用了一个projection。我想问 如果当时对Graph 中的node 进行Embedding的时候，Embedding模型和之后的Base model 的语义空间，差的很大的话，会不会造成效果很差呢

**Comment by XiaoxinHe** [comment]
我们当时研究了[不同的embedding方法](https://github.com/XiaoxinHe/G-Retriever/blob/a4baacdd5c2d12460b3881eb63b9b376e4ea18c3/src/utils/lm_modeling.py#L185)，包括word2vec、Sentence-BERT和Contriever。我们发现这些embedding方法之间的差距并不显著，且最优方法因数据集而异。word2vec是和base model (llama) 语义差距较大的模型了，但也没有出现效果特别差的情况。原因可能是在G-Retriever中，图上的语义（节点和边的属性）也被显式地表达，作为LLM的输入，这弥补了node/edge embedding的局限性。

**Comment by gaotongxue12138** [comment]
嗷嗷嗷，明白了谢谢！
