### ISSUE TITLE
Reproducibility time

### ISSUE THREAD

**Issue by RaghviBaloni** [XiaoxinHe/G-Retriever#7]
Your work is amazing!
Though I am facing issues reproducing experiments on WebQSP data. I am trying to replicate the project using READ.me in AWS Jupyter Notebook. The pre-processing of data is taking a lot of time. It shows the approximate time for pre-processing to be 1330 hours for graph encoding. Is it supposed to take this long?

**Comment by XiaoxinHe** [comment]
Hi,

Thank you for your interest in our work. Preprocessing WebQSP should not take long; it typically takes about 10 hours for WebQSP and 1-2 hours for the other two datasets. There should be a progress bar indicating the process and the estimated total time. Have you seen it in our output? If not, the program may have gotten stuck somewhere. Please let me know if you have further questions. Thanks!

**Comment by RaghviBaloni** [comment]
Thank you so much for quick response. I realised my instance wasn't using GPU at all. Now the pre-processing time is much faster!
